version: '3'
services:
  postgres:
    build:
      context: test_servers/postgres/
    volumes:
      - postgres-pipeline-data:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_PASSWORD=pword
  nfl-wiremock:
    image:
      rodolpheche/wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./test_servers/nfl_api:/home/wiremock/mappings
    command: >
      java -cp /var/wiremock/lib/*:/var/wiremock/extensions/*
      com.github.tomakehurst.wiremock.standalone.WireMockServerRunner
      --root-dir=mappings
#      --proxy-all="https://www.vegasinsider.com/"
#      --record-mappings

volumes:
  postgres-pipeline-data: