name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12'

    - name: Build client
      run: |
        cd client
        yarn install
        yarn build
    - name: Test client
      run: |
        cd client
        CI=true yarn test

    - name: Server test and build jar
      run: |
        cd server
        java -version
        gradle --version
        gradle --info build

    - name: Create server jar
      run: |
        cd server
        gradle jar

    - name: Build and start docker image
      run: |
        docker build . -t pickaxe
        docker run -d -p 8080:8080 pickaxe

    - name: Integration test
      run: |
        yarn install
        yarn run cypress run


